import { db } from "@db/connection";
import { additiveClassifications, haramKeywords } from "@db/schema";
import { logger } from "@utils/logger.util";

// =============================================================================
// ADDITIVE CLASSIFICATIONS
// Sources: IFANCA, JAKIM, Halal Foundation, Islamic scholars consensus
// Legend: haram = forbidden | doubtful = source-dependent/mashbooh | halal = permitted
// =============================================================================
const commonAdditives = [
  // ── HARAM ──────────────────────────────────────────────────────────────
  {
    code: "E120",
    name: "Carmine / Cochineal",
    halalStatus: "haram",
    source: "insect-derived",
    notes: "Red dye extracted from Dactylopius coccus insects. Haram per Hanafi, Shafi'i, Hanbali schools.",
  },
  {
    code: "E441",
    name: "Gelatin",
    halalStatus: "haram",
    source: "animal-derived",
    notes: "Typically pork-derived. Only halal if explicitly certified as fish/beef halal gelatin.",
  },
  {
    code: "E542",
    name: "Edible Bone Phosphate",
    halalStatus: "haram",
    source: "animal-bone",
    notes: "Derived from animal bones; haram unless from halal-slaughtered animals with certification.",
  },
  {
    code: "E901",
    name: "Beeswax",
    halalStatus: "haram",
    source: "insect-derived",
    notes: "Produced by honey bees; considered haram by many scholars as an insect secretion.",
  },
  {
    code: "E904",
    name: "Shellac",
    halalStatus: "haram",
    source: "insect-derived",
    notes: "Resin secreted by the lac insect. Haram per majority of scholars.",
  },
  {
    code: "E920",
    name: "L-Cysteine (from animal hair/feathers)",
    halalStatus: "haram",
    source: "animal-derived",
    notes: "When sourced from human hair or pig bristles. Doubtful/haram unless plant/microbial certified.",
  },

  // ── DOUBTFUL (Mashbooh) ─────────────────────────────────────────────────
  {
    code: "E470",
    name: "Sodium / Potassium / Calcium salts of fatty acids",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Fatty acids can be plant-based or animal-derived (including pork). Verify source.",
  },
  {
    code: "E471",
    name: "Mono- and diglycerides of fatty acids",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Most common emulsifier. Can be from vegetable oils (halal) or animal fats (haram). No way to tell without manufacturer confirmation.",
  },
  {
    code: "E472",
    name: "Esters of mono- and diglycerides",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Includes E472a–f (acetic, lactic, citric, tartaric esters). Source-dependent.",
  },
  {
    code: "E472A",
    name: "Acetic acid esters of mono/diglycerides",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Source-dependent; verify with manufacturer.",
  },
  {
    code: "E472B",
    name: "Lactic acid esters of mono/diglycerides",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Source-dependent; verify with manufacturer.",
  },
  {
    code: "E472C",
    name: "Citric acid esters of mono/diglycerides",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Source-dependent; verify with manufacturer.",
  },
  {
    code: "E472D",
    name: "Tartaric acid esters of mono/diglycerides",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Source-dependent; verify with manufacturer.",
  },
  {
    code: "E472E",
    name: "Acetyltartaric acid esters of mono/diglycerides",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Source-dependent; verify with manufacturer.",
  },
  {
    code: "E472F",
    name: "Mixed tartaric and acetic acid esters of mono/diglycerides",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Source-dependent; verify with manufacturer.",
  },
  {
    code: "E473",
    name: "Sucrose esters of fatty acids",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Fatty acid portion can be animal-derived.",
  },
  {
    code: "E474",
    name: "Sucroglycerides",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Source-dependent on fatty acids used.",
  },
  {
    code: "E475",
    name: "Polyglycerol esters of fatty acids",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Source-dependent on fatty acids used.",
  },
  {
    code: "E476",
    name: "Polyglycerol polyricinoleate (PGPR)",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Usually castor-oil/plant-derived but can vary. Verify source.",
  },
  {
    code: "E477",
    name: "Propylene glycol esters of fatty acids",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Source-dependent on fatty acids used.",
  },
  {
    code: "E478",
    name: "Lactylated glycerol esters of fatty acids",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Source-dependent.",
  },
  {
    code: "E479",
    name: "Thermally oxidized soya bean oil with mono/diglycerides",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "May contain animal-derived diglycerides.",
  },
  {
    code: "E481",
    name: "Sodium stearoyl lactylate (SSL)",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Stearic acid can be animal-derived.",
  },
  {
    code: "E482",
    name: "Calcium stearoyl lactylate (CSL)",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Stearic acid can be animal-derived.",
  },
  {
    code: "E483",
    name: "Stearyl tartrate",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Stearic acid can be animal-derived.",
  },
  {
    code: "E491",
    name: "Sorbitan monostearate",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Stearic acid can be animal-derived.",
  },
  {
    code: "E492",
    name: "Sorbitan tristearate",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Stearic acid can be animal-derived.",
  },
  {
    code: "E493",
    name: "Sorbitan monolaurate",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Lauric acid source can vary.",
  },
  {
    code: "E494",
    name: "Sorbitan monooleate",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Oleic acid source can vary.",
  },
  {
    code: "E495",
    name: "Sorbitan monopalmitate",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Palmitic acid typically plant-based but verify.",
  },
  {
    code: "E570",
    name: "Fatty acids (Stearic acid)",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Can be plant or animal-derived.",
  },
  {
    code: "E572",
    name: "Magnesium stearate",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Stearic acid can be animal-derived.",
  },
  {
    code: "E631",
    name: "Disodium inosinate",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Often derived from meat or fish; pork origin possible. Verify with manufacturer.",
  },
  {
    code: "E635",
    name: "Disodium 5'-ribonucleotides",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Blend of E627 + E631; animal origin possible.",
  },
  {
    code: "E627",
    name: "Disodium guanylate",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Often derived from yeast or meat. Verify source.",
  },
  {
    code: "E422",
    name: "Glycerol / Glycerin",
    halalStatus: "doubtful",
    source: "mixed",
    notes: "Can be plant-based (halal) or animal/pork tallow-derived (haram). Verify origin.",
  },

  // ── HALAL ───────────────────────────────────────────────────────────────
  {
    code: "E100",
    name: "Curcumin",
    halalStatus: "halal",
    source: "plant-based",
    notes: "Turmeric-derived natural colourant.",
  },
  {
    code: "E101",
    name: "Riboflavin (Vitamin B2)",
    halalStatus: "halal",
    source: "synthetic/plant",
    notes: null,
  },
  {
    code: "E140",
    name: "Chlorophylls",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E150A",
    name: "Plain caramel",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E150B",
    name: "Caustic sulphite caramel",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E150C",
    name: "Ammonia caramel",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E150D",
    name: "Sulphite ammonia caramel",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E160A",
    name: "Beta-carotene",
    halalStatus: "halal",
    source: "plant/synthetic",
    notes: null,
  },
  {
    code: "E200",
    name: "Sorbic acid",
    halalStatus: "halal",
    source: "synthetic",
    notes: "Preservative.",
  },
  {
    code: "E202",
    name: "Potassium sorbate",
    halalStatus: "halal",
    source: "synthetic",
    notes: "Preservative.",
  },
  {
    code: "E210",
    name: "Benzoic acid",
    halalStatus: "halal",
    source: "synthetic",
    notes: "Preservative.",
  },
  {
    code: "E211",
    name: "Sodium benzoate",
    halalStatus: "halal",
    source: "synthetic",
    notes: "Preservative.",
  },
  {
    code: "E260",
    name: "Acetic acid",
    halalStatus: "halal",
    source: "synthetic",
    notes: "Vinegar acid; halal when not derived from alcohol fermentation.",
  },
  {
    code: "E270",
    name: "Lactic acid",
    halalStatus: "halal",
    source: "fermentation",
    notes: "Fermentation-derived; halal.",
  },
  {
    code: "E296",
    name: "Malic acid",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E300",
    name: "Ascorbic acid (Vitamin C)",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E301",
    name: "Sodium ascorbate",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E302",
    name: "Calcium ascorbate",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E306",
    name: "Mixed tocopherols (Vitamin E)",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E307",
    name: "Alpha-tocopherol (Vitamin E)",
    halalStatus: "halal",
    source: "plant/synthetic",
    notes: null,
  },
  {
    code: "E322",
    name: "Lecithins",
    halalStatus: "halal",
    source: "plant-based",
    notes: "Usually soy or sunflower lecithin. Halal.",
  },
  {
    code: "E322I",
    name: "Soy lecithin",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E325",
    name: "Sodium lactate",
    halalStatus: "halal",
    source: "fermentation",
    notes: null,
  },
  {
    code: "E330",
    name: "Citric acid",
    halalStatus: "halal",
    source: "fermentation/synthetic",
    notes: null,
  },
  {
    code: "E331",
    name: "Sodium citrates",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E332",
    name: "Potassium citrates",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E334",
    name: "Tartaric acid",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E335",
    name: "Sodium tartrates",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E400",
    name: "Alginic acid",
    halalStatus: "halal",
    source: "seaweed",
    notes: null,
  },
  {
    code: "E401",
    name: "Sodium alginate",
    halalStatus: "halal",
    source: "seaweed",
    notes: null,
  },
  {
    code: "E406",
    name: "Agar",
    halalStatus: "halal",
    source: "seaweed",
    notes: "Plant-based gelatin alternative.",
  },
  {
    code: "E407",
    name: "Carrageenan",
    halalStatus: "halal",
    source: "seaweed",
    notes: null,
  },
  {
    code: "E410",
    name: "Locust bean gum",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E412",
    name: "Guar gum",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E414",
    name: "Arabic gum / Acacia gum",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E415",
    name: "Xanthan gum",
    halalStatus: "halal",
    source: "microbial-fermentation",
    notes: null,
  },
  {
    code: "E418",
    name: "Gellan gum",
    halalStatus: "halal",
    source: "microbial-fermentation",
    notes: null,
  },
  {
    code: "E440",
    name: "Pectins",
    halalStatus: "halal",
    source: "plant-based",
    notes: "Derived from fruit peel; halal vegetarian gelatin alternative.",
  },
  {
    code: "E500",
    name: "Sodium carbonates",
    halalStatus: "halal",
    source: "mineral",
    notes: null,
  },
  {
    code: "E501",
    name: "Potassium carbonates",
    halalStatus: "halal",
    source: "mineral",
    notes: null,
  },
  {
    code: "E503",
    name: "Ammonium carbonates",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E504",
    name: "Magnesium carbonates",
    halalStatus: "halal",
    source: "mineral",
    notes: null,
  },
  {
    code: "E508",
    name: "Potassium chloride",
    halalStatus: "halal",
    source: "mineral",
    notes: null,
  },
  {
    code: "E509",
    name: "Calcium chloride",
    halalStatus: "halal",
    source: "mineral",
    notes: null,
  },
  {
    code: "E516",
    name: "Calcium sulphate",
    halalStatus: "halal",
    source: "mineral",
    notes: null,
  },
  {
    code: "E621",
    name: "Monosodium glutamate (MSG)",
    halalStatus: "halal",
    source: "fermentation/synthetic",
    notes: "Halal when fermentation medium is plant-based (most commercial MSG is).",
  },
  {
    code: "E950",
    name: "Acesulfame K",
    halalStatus: "halal",
    source: "synthetic",
    notes: "Artificial sweetener.",
  },
  {
    code: "E951",
    name: "Aspartame",
    halalStatus: "halal",
    source: "synthetic",
    notes: "Artificial sweetener.",
  },
  {
    code: "E952",
    name: "Cyclamates",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E954",
    name: "Saccharin",
    halalStatus: "halal",
    source: "synthetic",
    notes: null,
  },
  {
    code: "E960",
    name: "Steviol glycosides",
    halalStatus: "halal",
    source: "plant-based",
    notes: "Derived from Stevia plant.",
  },
  {
    code: "E965",
    name: "Maltitol",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E1400",
    name: "Dextrin",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E1404",
    name: "Oxidized starch",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E1420",
    name: "Acetylated starch",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E1442",
    name: "Hydroxypropyl distarch phosphate",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
  {
    code: "E1450",
    name: "Starch sodium octenylsuccinate",
    halalStatus: "halal",
    source: "plant-based",
    notes: null,
  },
];

// =============================================================================
// HARAM KEYWORDS
// Comprehensive list of ingredient names / terms covering:
//   - Pork and all its derivatives
//   - Alcohol and alcoholic beverages
//   - Blood and blood products
//   - Insect-derived substances
//   - Ambiguous/doubtful animal-derived terms
// =============================================================================
const haramKeywordsList = [
  // ── PORK & PORK DERIVATIVES (Haram) ──────────────────────────────────
  { keyword: "pork", status: "haram", category: "pork", notes: "Swine flesh; forbidden in Islam." },
  { keyword: "pork fat", status: "haram", category: "pork", notes: null },
  { keyword: "pork rind", status: "haram", category: "pork", notes: null },
  { keyword: "pork lard", status: "haram", category: "pork", notes: null },
  { keyword: "pork extract", status: "haram", category: "pork", notes: null },
  { keyword: "pork gelatin", status: "haram", category: "pork", notes: null },
  { keyword: "pork enzymes", status: "haram", category: "pork", notes: null },
  { keyword: "pork liver", status: "haram", category: "pork", notes: null },
  { keyword: "bacon", status: "haram", category: "pork", notes: null },
  { keyword: "ham", status: "haram", category: "pork", notes: "Use word-boundary check to avoid matching 'mushroom'." },
  { keyword: "ham flavour", status: "haram", category: "pork", notes: null },
  { keyword: "pancetta", status: "haram", category: "pork", notes: null },
  { keyword: "prosciutto", status: "haram", category: "pork", notes: null },
  { keyword: "salami", status: "haram", category: "pork", notes: null },
  { keyword: "pepperoni", status: "haram", category: "pork", notes: null },
  { keyword: "chorizo", status: "haram", category: "pork", notes: null },
  { keyword: "mortadella", status: "haram", category: "pork", notes: null },
  { keyword: "lard", status: "haram", category: "pork", notes: "Rendered pork fat." },
  { keyword: "pig fat", status: "haram", category: "pork", notes: null },
  { keyword: "pig skin", status: "haram", category: "pork", notes: null },
  { keyword: "pig liver", status: "haram", category: "pork", notes: null },
  { keyword: "swine", status: "haram", category: "pork", notes: null },
  { keyword: "porcine", status: "haram", category: "pork", notes: "Pork-derived; seen in gelatin/enzyme labelling." },
  { keyword: "porcine gelatin", status: "haram", category: "pork", notes: null },
  { keyword: "porcine enzyme", status: "haram", category: "pork", notes: null },
  { keyword: "suet", status: "doubtful", category: "pork", notes: "Raw fat around kidneys; can be beef or pork. Verify source." },

  // ── ALCOHOL & SPIRITS (Haram) ─────────────────────────────────────────
  { keyword: "alcohol", status: "haram", category: "alcohol", notes: "Any form of ethyl alcohol used as ingredient." },
  { keyword: "ethanol", status: "haram", category: "alcohol", notes: "Active alcohol compound." },
  { keyword: "ethyl alcohol", status: "haram", category: "alcohol", notes: null },
  { keyword: "wine", status: "haram", category: "alcohol", notes: null },
  { keyword: "red wine", status: "haram", category: "alcohol", notes: null },
  { keyword: "white wine", status: "haram", category: "alcohol", notes: null },
  { keyword: "rice wine", status: "haram", category: "alcohol", notes: null },
  { keyword: "cooking wine", status: "haram", category: "alcohol", notes: null },
  { keyword: "beer", status: "haram", category: "alcohol", notes: null },
  { keyword: "rum", status: "haram", category: "alcohol", notes: null },
  { keyword: "vodka", status: "haram", category: "alcohol", notes: null },
  { keyword: "whisky", status: "haram", category: "alcohol", notes: null },
  { keyword: "whiskey", status: "haram", category: "alcohol", notes: null },
  { keyword: "brandy", status: "haram", category: "alcohol", notes: null },
  { keyword: "liqueur", status: "haram", category: "alcohol", notes: null },
  { keyword: "champagne", status: "haram", category: "alcohol", notes: null },
  { keyword: "sake", status: "haram", category: "alcohol", notes: "Japanese rice wine." },
  { keyword: "mead", status: "haram", category: "alcohol", notes: null },
  { keyword: "tequila", status: "haram", category: "alcohol", notes: null },
  { keyword: "gin", status: "haram", category: "alcohol", notes: null },
  { keyword: "schnapps", status: "haram", category: "alcohol", notes: null },
  { keyword: "absinthe", status: "haram", category: "alcohol", notes: null },
  { keyword: "bourbon", status: "haram", category: "alcohol", notes: null },
  { keyword: "port wine", status: "haram", category: "alcohol", notes: null },
  { keyword: "marsala", status: "haram", category: "alcohol", notes: null },
  { keyword: "sherry", status: "haram", category: "alcohol", notes: null },
  { keyword: "wine vinegar", status: "haram", category: "alcohol", notes: "Retains trace alcohol." },
  { keyword: "sherry vinegar", status: "haram", category: "alcohol", notes: null },
  { keyword: "malt vinegar", status: "haram", category: "alcohol", notes: "Fermented from barley/ale; trace alcohol." },
  { keyword: "vanilla extract", status: "haram", category: "alcohol", notes: "Traditional extract uses ethanol solvent. Use vanilla flavour/powder instead." },
  { keyword: "rum extract", status: "haram", category: "alcohol", notes: null },
  { keyword: "bourbon vanilla", status: "haram", category: "alcohol", notes: null },

  // ── BLOOD & CARRION (Haram) ───────────────────────────────────────────
  { keyword: "blood", status: "haram", category: "blood", notes: "Consuming blood is explicitly forbidden in Quran." },
  { keyword: "blood plasma", status: "haram", category: "blood", notes: null },
  { keyword: "dried blood", status: "haram", category: "blood", notes: null },
  { keyword: "blood meal", status: "haram", category: "blood", notes: null },
  { keyword: "blood sausage", status: "haram", category: "blood", notes: null },
  { keyword: "black pudding", status: "haram", category: "blood", notes: "Blood sausage." },

  // ── INSECT-DERIVED (Haram per majority) ──────────────────────────────
  { keyword: "carmine", status: "haram", category: "insect", notes: "Red dye from crushed Dactylopius coccus. E120." },
  { keyword: "cochineal", status: "haram", category: "insect", notes: "Same as carmine. Insect-derived." },
  { keyword: "natural red 4", status: "haram", category: "insect", notes: "Another name for carmine." },

  // ── DOUBTFUL / MASHBOOH ───────────────────────────────────────────────
  {
    keyword: "gelatin",
    status: "doubtful",
    category: "animal-product",
    notes: "Usually pork-derived unless explicitly labelled as fish gelatin or halal beef gelatin.",
  },
  {
    keyword: "gelatine",
    status: "doubtful",
    category: "animal-product",
    notes: "British spelling of gelatin.",
  },
  {
    keyword: "beef gelatin",
    status: "doubtful",
    category: "animal-product",
    notes: "Halal only if slaughtered according to Islamic rites and certified.",
  },
  {
    keyword: "rennet",
    status: "doubtful",
    category: "enzyme",
    notes: "Often derived from calf stomach (non-zabiha). Halal only if microbial or certified halal animal rennet.",
  },
  {
    keyword: "animal rennet",
    status: "haram",
    category: "enzyme",
    notes: "Derived from non-zabiha animal stomach; haram unless certified.",
  },
  {
    keyword: "pepsin",
    status: "doubtful",
    category: "enzyme",
    notes: "Digestive enzyme from animal (often pork) stomach. Verify source.",
  },
  {
    keyword: "lipase",
    status: "doubtful",
    category: "enzyme",
    notes: "Can be animal (including pork) or microbial derived.",
  },
  {
    keyword: "tallow",
    status: "doubtful",
    category: "fat",
    notes: "Rendered animal fat (beef/sheep). Halal only if from zabiha-slaughtered animals.",
  },
  {
    keyword: "beef tallow",
    status: "doubtful",
    category: "fat",
    notes: "Halal only if zabiha-certified.",
  },
  {
    keyword: "animal fat",
    status: "doubtful",
    category: "fat",
    notes: "Source and slaughter method unknown without labelling.",
  },
  {
    keyword: "animal shortening",
    status: "doubtful",
    category: "fat",
    notes: "Source unknown; could be lard.",
  },
  {
    keyword: "shortening",
    status: "doubtful",
    category: "fat",
    notes: "When source is not specified as vegetable; may be animal fat.",
  },
  {
    keyword: "chicken fat",
    status: "doubtful",
    category: "fat",
    notes: "Halal only if from zabiha-slaughtered chicken.",
  },
  {
    keyword: "beef extract",
    status: "doubtful",
    category: "meat",
    notes: "Halal only if from zabiha-slaughtered cattle.",
  },
  {
    keyword: "meat extract",
    status: "doubtful",
    category: "meat",
    notes: "Source and slaughter method unknown.",
  },
  {
    keyword: "natural flavor",
    status: "doubtful",
    category: "flavouring",
    notes: "May contain alcohol solvents or animal-derived components.",
  },
  {
    keyword: "natural flavour",
    status: "doubtful",
    category: "flavouring",
    notes: "British spelling; same concern as natural flavor.",
  },
  {
    keyword: "natural flavors",
    status: "doubtful",
    category: "flavouring",
    notes: "Plural form; same concern.",
  },
  {
    keyword: "natural flavours",
    status: "doubtful",
    category: "flavouring",
    notes: "Plural British form.",
  },
  {
    keyword: "l-cysteine",
    status: "doubtful",
    category: "amino-acid",
    notes: "Dough conditioner. Often sourced from human hair, pig bristles, or poultry feathers. Halal only if plant/microbial.",
  },
  {
    keyword: "cysteine",
    status: "doubtful",
    category: "amino-acid",
    notes: "Same source concern as L-cysteine.",
  },
  {
    keyword: "glycerin",
    status: "doubtful",
    category: "additive",
    notes: "Can be plant-based (halal) or from tallow/pork fat (haram). Verify source.",
  },
  {
    keyword: "glycerol",
    status: "doubtful",
    category: "additive",
    notes: "Same as glycerin; verify origin.",
  },
  {
    keyword: "mono and diglycerides",
    status: "doubtful",
    category: "emulsifier",
    notes: "E471 — can be plant or animal-derived.",
  },
  {
    keyword: "monoglycerides",
    status: "doubtful",
    category: "emulsifier",
    notes: "Source-dependent.",
  },
  {
    keyword: "diglycerides",
    status: "doubtful",
    category: "emulsifier",
    notes: "Source-dependent.",
  },
  {
    keyword: "stearic acid",
    status: "doubtful",
    category: "fatty-acid",
    notes: "Can be plant or animal-derived.",
  },
  {
    keyword: "oleic acid",
    status: "doubtful",
    category: "fatty-acid",
    notes: "Usually plant-derived but can be from tallow.",
  },
  {
    keyword: "lactoferrin",
    status: "doubtful",
    category: "protein",
    notes: "Whey protein fraction; permissible if from halal-certified dairy.",
  },
  {
    keyword: "shellac",
    status: "doubtful",
    category: "insect",
    notes: "Insect resin (E904). Haram per many scholars.",
  },
  {
    keyword: "beeswax",
    status: "doubtful",
    category: "insect",
    notes: "E901. Haram per many scholars; permissible per Maliki school.",
  },
];

export async function seedHalalData() {
  try {
    logger.info("Seeding comprehensive halal classification data...");

    // Seed additives
    let additivesSeeded = 0;
    for (const additive of commonAdditives) {
      await db
        .insert(additiveClassifications)
        .values(additive)
        .onConflictDoNothing();
      additivesSeeded++;
    }

    // Seed keywords
    let keywordsSeeded = 0;
    for (const keyword of haramKeywordsList) {
      await db.insert(haramKeywords).values(keyword).onConflictDoNothing();
      keywordsSeeded++;
    }

    logger.info(
      `✅ Seeded ${additivesSeeded} additives and ${keywordsSeeded} keywords`,
    );
  } catch (error) {
    logger.error(`Failed to seed halal data: ${(error as Error).message}`);
  }
}

// Run if called directly
if (import.meta.main) {
  seedHalalData().then(() => process.exit(0));
}
